version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
        php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Loggin into AWS ECR "
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo "Tag the image"
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - echo "Push to the ECR"
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG